### ISSUE TITLE
Воровать не хорошо)

### ISSUE THREAD

**Issue by on3dd** [mamkinbyntar/Test2#1]
Зачем ты форкнул мою репу, чтобы перезалить ее под своим именем?) Не стыдно, друг?) https://github.com/on3dd/vue-simon-the-game

P.S.: Успешного собеседования с чужим кодом)

**Comment by mamkinbyntar** [comment]
Прости друг, но надо как-то зачёт по js закрыть...

чт, 17 февр. 2022 г., 10:56 Artyom ***@***.***>:

**Comment by on3dd** [comment]
:D
